
version: '3.0'
services:
  web:
    image: enthyp/io-lab-docker-ci-public:latest
    ports: 
      - 5000:5000
    depends_on: 
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc3
    volumes: 
      - ./data:/data
